title: Legend of Red Dragon (LoRD) Wiki
description: Wiki for the legendreddragon.net version of LoRD
theme: just-the-docs

url: https://lord.github.io

aux_links:
  Template Repository: https://legendreddragon.net
